databases:
  - name: love_letter_backend_db
    plan: free
    databaseName: love_letter_backend
    user: love_letter_backend

services:
  - type: web
    plan: free
    name: love_letter_backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn Love_Letter_Backend.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: love_letter_backend_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
